[INFRA] Permettre à Pix Bot d'invalider le cache de notre CDN
1024pix/pix-bot pull request #46
Opened 2020-12-18 15:44 UTC by VincentHardouin

## :unicorn: Problème
Le cache de notre CDN s'actualise toutes les 4h. Ce délais pouvant engendrait des demandes de la part de l'équipe communication pour actualiser le site. Nous décidons de faire en sorte que chaque modification faites soit directement disponible en production. 

## :robot: Solution
Mettre en place un endpoint permettant d'invalider le cache CDN d'une application. 
Cet endpoint servira de webhook et sera appelé par Scalingo lorsque le déploiement de l'application sera finie.

Nous avons choisi d'appeler l'endpoint en suivant le nommage de Baleen : 
`api/applications/{name}/cdn-cache-invalidations`

Nous avons sécurisé l'endpoint à l'aide de l'openApi token déjà présent dans Pix Bot. Ce dernier sera passé en queryParams : `?openApi=token`.  

Nous avons du ajouté de variable d'environnement : 
La première : `BALEEN_PERSONAL_ACCESS_TOKEN` permettant d'authentifier les appels.
La seconde : `BALEEN_APP_NAMESPACES` jouant le rôle de table de correspondance entre un namespace Baleen et le nom d'une application Pix. 
 

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2020-12-31 13:48 UTC, francois2metz approved these changes
LGTM

2021-01-04 15:42 UTC, jbuget requested changes
Quelques petites modifs nécessaires à mon sens.

2021-01-04 15:42 UTC, jbuget commented on lib/services/cdn.js
> +  const urlForAccountDetails = 'https://console.baleen.cloud/api/account';
Vu qu'on l'utilise à 2 reprises, j'aurais sorti le _endpoint_ de l'API Baleen - `https://console.baleen.cloud/api/` - dans une const ci-dessus.

2021-01-04 15:42 UTC, jbuget commented on lib/services/cdn.js
> +  const namespace = _.find(namespaces, (v,k) => { return k === application; });
Si j'étais précis (et qu'on avait un linter sur Pix Bot), je dirais qu'il manque un espace : `(v,k) =>`…

2021-01-04 15:42 UTC, jbuget commented on lib/services/cdn.js
> +  return undefined;
Je pense qu'il est préférable de lever une Erreur.

2021-01-04 15:42 UTC, jbuget commented on test/integration/lib/controllers/applications_test.js
> +
Ligne en trop

2021-01-04 15:42 UTC, jbuget commented on test/integration/lib/services/cdn_test.js
> +  });
Je rajouterais bien un test en cas d'erreur, notamment si le application name n'est pas bon

2021-01-05 09:18 UTC, jbuget approved these changes

2021-01-05 09:19 UTC, chrc commented on lib/services/cdn.js
> +  const namespace = _.find(namespaces, (v,k) => { return k === application; });
Suggestion : On peut ajouter dans le fichier `.eslintrc.js` 
```javascript
'root': true,
```

2021-01-05 09:19 UTC, merged